package com.pfe.parc.informatique.entities;

public enum EDepartment {
    DEPARTMENT_DIRECTION_GENERALE,
    DEPARTMENT_DIRECTION_TECHNIQUE,
    DEPARTMENT_DIRECTION_DES_ETUDES_ET_DE_LA_PLANIFICATION,
    DEPARTMENT_DIRECTION_DE_LA_REGLEMENTATION,
    DEPARTMENT_DIRECTION_DE_LA_SURVEILLANCE,
    DEPARTMENT_DIRECTION_DE_LA_GESTION_DES_FREQUENCES,
    DEPARTMENT_DIRECTION_DES_RESSOURCES_HUMAINES,
    DEPARTMENT_DIRECTION_DES_FINANCES,
    DEPARTMENT_DIRECTION_DE_L_INFORMATIQUE,
    DEPARTMENT_DIRECTION_DE_LA_COMMUNICATION,
    DEPARTMENT_DIRECTION_DES_AFFAIRES_JURIDIQUES
}
